# Generated by Django 5.0.6 on 2024-05-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(default='nan', max_length=255),
            preserve_default=False,
        ),
    ]
